### PR TITLE
Korean Localization for 1.16.5

### PR DESCRIPTION
**Pull request by gjeodnd12165**
I'm not sure there are some encoding errors.
There would be no untranslated words now.

ps. How do I update changes in existing pull request without closing and making another pull request like this?

### CODE REVIEW

**Comment by Epic428** [comment]
Should be able to just push the changes to the same branch and it’ll get marked as a new commit in the PR

**Comment by gjeodnd12165** [comment]
> Should be able to just push the changes to the same branch and it’ll get marked as a new commit in the PR

Thank you for your reply! I'll have to do that next time.


There is a check failed. What is telling about? I think it seems the problem with dependencies...?

**Comment by Epic428** [comment]
Ah it was sonar. Failed for a stupid reason. I’d ignore it. But if the translations are good for the 1.16.5 version I can merge the PR. As a side note I would avoid translations on our 1.18 version atm as it is still a WIP and evolving. I just need to get some time to get back to work on it.

**Comment by gjeodnd12165** [comment]
Oh, it works! Thank you for teaching.
There was another untranslated string and are some changes.

It'll probably be good for 1.16.5, and I'd be happy if you could merge my localizations.


If my understanding is correct, you are saying that there will be more features in 1.18 and some changed or added strings?
I can't wait for playing Resourceful Bees in 1.18!

**Comment by ThatGravyBoat** [comment]
Yes if not almost all translations most translations have been changed in some way in our 1.18 dev build and still are changing

**Comment by ThatGravyBoat** [comment]
Thanks for the translations!

**Pull request merged**
