### PR TITLE
1.16.5  optimization

### PR DESCRIPTION
**Pull request by PandaEzWin**

### CODE REVIEW

**Comment by Vaerys-Dawn** [comment]
This version of the mod has ceased feature development, and unless there is a major bug that needs fixing there will likely not be any new versions added to curse forge.

You are more than welcome to attempt to fix this on the 1.0.0 build if we haven't already.

**Comment by Epic428** [comment]
Honestly I would be ok with merging the PR in. I wouldn’t push out an update unless it’s a massive/critical optimization. But at least then if we do end up needing to push an update it’ll be included and not overlooked.

**Comment by Vaerys-Dawn** [comment]
well one optimisation that we'd have to revert is that they turned `TraitConstants.CLINGY` to just "clingy", but other than that it should be fine, I understand that it's faster to serialise? strings but Imo consistency is more important

**Comment by Epic428** [comment]
I mean there’s negligible difference between “clingy” and TraitConstants.CLINGY because the latter should be inlined anyway due to being public static final.

**Pull request closed without merging**
